# Generated by Django 6.1 on 2026-08-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.SlugField(help_text='e.g. BPW, LATVIA, SSH, HOR', unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('config', models.JSONField(help_text='Field -> extraction rule mapping. See mappings/*.json for examples.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'ordering': ['project_key'],
            },
        ),
    ]
