# Generated by Django 6.1 on 2026-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
