# Generated by Django 6.1 on 2026-08-17 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_key', models.SlugField(help_text='Matches the ProjectTemplate.project_key it was imported with')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_records', models.BigIntegerField(default=0)),
                ('delivered_records', models.BigIntegerField(default=0)),
                ('total_images', models.BigIntegerField(default=0)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('event_type', models.CharField(blank=True, default='', max_length=150)),
                ('ocr_status', models.CharField(blank=True, default='', max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('google_sheet_url', models.URLField(blank=True, default='', max_length=500)),
                ('sync_token', models.CharField(blank=True, default='', max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='branches.branch')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('project_key', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_template_key', models.SlugField()),
                ('file_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('FILE', 'Excel Upload'), ('GOOGLE_SHEET', 'Google Sheet')], default='FILE', max_length=15)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
