# Generated by Django 6.1 on 2026-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batches_being_keyed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='promoted',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_batches',
            field=models.BigIntegerField(default=0),
        ),
    ]
