# Generated by Django 6.0.8 on 2026-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_batches_being_keyed_project_promoted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible_inventory_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
