# Generated by Django 6.0.8 on 2026-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_visible_inventory_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='defined_custom_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
