# Generated by Django 6.1 on 2026-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_defined_custom_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivered_column_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='received_column_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
