# Generated by Django 6.1 on 2026-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_delivered_column_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batches_keyed_value',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='batches_status_column_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
