# Generated by Django 6.1 on 2026-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_batches_keyed_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batches_end_date_column_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
