# Generated by Django 6.1 on 2026-08-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_batches_end_date_column_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
