# Generated by Django 6.1 on 2026-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_dailyoperationalmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Customer Name'),
        ),
    ]
