# Generated by Django 6.1 on 2026-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestone_100_date',
            field=models.DateField(blank=True, null=True, verbose_name='100% Milestone Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='milestone_10_date',
            field=models.DateField(blank=True, null=True, verbose_name='10% Milestone Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='milestone_50_date',
            field=models.DateField(blank=True, null=True, verbose_name='50% Milestone Date'),
        ),
    ]
