# Generated by Django 6.1 on 2026-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'General Manager'), ('PL', 'Project Lead'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10),
        ),
    ]
