# Generated by Django 6.0.8 on 2026-08-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
        ('branches', '0001_initial'),
        ('projects', '0008_project_summary_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Which SPECIFIC projects this user can see/manage, on top of branch access. Only enforced for Project Manager and Viewer roles - Admin/Branch Manager/Project Lead are governed by branch access alone and ignore this field. Leave empty for PM/Viewer to grant no project access yet.', related_name='assigned_profiles', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Which branches this user can see/manage. Ignored for ADMIN (always full access). Leave empty for MANAGER/PL/PM/VIEWER to grant no branch access yet.', related_name='user_profiles', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Branch Manager'), ('PL', 'Project Lead'), ('PM', 'Project Manager'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10),
        ),
    ]
