# Generated by Django 6.0.8 on 2026-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_projects_alter_userprofile_branches_and_more'),
        ('projects', '0008_project_summary_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Which SPECIFIC projects this user can see/manage, on top of branch access. Only enforced for Project Manager, Project Lead, and Viewer roles - Admin/Branch Manager are governed by branch access alone and ignore this field. Leave empty for PM/PL/Viewer to grant no project access yet.', related_name='assigned_profiles', to='projects.project'),
        ),
    ]
