# Generated by Django 6.1 on 2026-08-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=150)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('image_count', models.BigIntegerField(default=0)),
                ('record_count', models.BigIntegerField(default=0)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='projects.project')),
            ],
            options={
                'ordering': ['-shipment_date', 'file_name'],
            },
        ),
    ]
